import { test, expect, type Page } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import { randomUUID } from 'node:crypto'

const env = () => ({ PATH: process.env.PATH, DATABASE_URL: process.env.TEST_DATABASE_URL, MIGRATE_ON_START: 'true' })
async function pair(page: Page, profile = 'memory') {
  const code = execFileSync('../../server/edu-agentd', ['pairing-code', 'create', '--profile', profile], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], env: env() }).trim()
  await page.goto('/app/')
  await page.getByLabel('配对码', { exact: true }).fill(code)
  const paired = page.waitForResponse(response => response.url().endsWith('/v1/web/pairings') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '配对并进入' }).click()
  expect((await paired).status()).toBe(201)
  await expect(page.getByRole('heading', { name: '今天想学会什么？' })).toBeVisible()
}
async function confirm(page: Page, label: string) {
  await page.getByRole('button', { name: label, exact: true }).click()
  const dialog = page.getByRole('alertdialog')
  await expect(dialog.getByRole('button', { name: '取消', exact: true })).toBeFocused()
  await dialog.getByRole('button', { name: `确认${label}`, exact: true }).click()
}

test('记忆候选显式批准、拒绝、真实排队导出与移动焦点', async ({ page }) => {
  await pair(page)
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/app/memory')
  await expect(page.getByText(/未按学习区隔离/).first()).toBeVisible()
  await page.getByRole('button', { name: '新建偏好候选', exact: true }).click()
  const content = `我偏好分步骤解释 ${randomUUID()}`
  await page.getByLabel('具体内容', { exact: true }).fill(content)
  await page.getByLabel('保存或纠正理由').fill('稳定偏好，逐条审阅')
  await page.getByRole('button', { name: '创建待审阅候选' }).click()
  await page.getByRole('link', { name: '查看具体候选并审批' }).click()
  const candidateURL = page.url()
  const review = page.getByRole('region', { name: '记忆候选详情' })
  await expect(review).toContainText(content)
  await expect(review).toContainText('待明确批准')
  for (const width of [390, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.getByRole('button', { name: '批准此条记忆', exact: true }).click()
  await expect(page.getByRole('alertdialog').getByRole('button', { name: '取消', exact: true })).toBeFocused()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.reload()
  await expect(review).toContainText('待明确批准')
  await confirm(page, '批准此条记忆')
  await expect(review.getByRole('link', { name: '查看真实记录与交付回执' })).toBeVisible()
  await review.getByRole('link', { name: '查看真实记录与交付回执' }).click()
  await expect(page.getByText('仍在等待，不宣称完成', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: '提出纠正', exact: true })).toBeDisabled()
  const downloaded = page.waitForEvent('download')
  await confirm(page, '导出本页长期记忆')
  const download = await downloaded
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  const exported = JSON.parse(Buffer.concat(chunks).toString())
  expect(exported.scope).toContain('全局')
  expect(exported.degraded).toBe(true)
  expect(JSON.stringify(exported)).not.toContain(content)
  await page.goto('/app/memory')
  await page.getByRole('button', { name: '新建偏好候选', exact: true }).click()
  await page.getByLabel('具体内容', { exact: true }).fill('拒绝的候选不应成为记忆')
  await page.getByLabel('保存或纠正理由').fill('测试拒绝')
  await page.getByRole('button', { name: '创建待审阅候选' }).click()
  await page.getByRole('link', { name: '查看具体候选并审批' }).click()
  await confirm(page, '拒绝此候选')
  await expect(review).not.toContainText('拒绝的候选不应成为记忆')
  await page.goto(candidateURL)
  await expect(page.getByRole('button', { name: '批准此条记忆', exact: true })).toBeDisabled()
  expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))).not.toContain(content)
  expect(errors).toEqual([])
})

test('设备撤销即时失效、隐私清除重新配对核对原回执', async ({ page, browser }) => {
  await pair(page)
  const session = await (await page.request.get('/v1/web/session')).json()
  const other = await browser.newContext()
  const victim = await other.newPage()
  await pair(victim)
  const victimSession = await (await victim.request.get('/v1/web/session')).json()
  await page.goto('/app/settings/devices')
  const device = page.locator('article').filter({ hasText: victimSession.device.id })
  await device.getByRole('button', { name: '撤销设备', exact: true }).click()
  await page.getByRole('button', { name: '确认撤销设备', exact: true }).click()
  await expect.poll(async () => (await victim.request.get('/v1/web/session')).status()).toBe(401)
  await other.close()
  const grant = execFileSync('../../server/edu-agentd', ['privacy-grant', 'create', '--device', session.device.id], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], env: env() }).trim()
  await page.goto('/app/settings/data')
  await page.getByLabel('一次性清除授权').fill(grant)
  const erased = page.waitForResponse(response => response.url().endsWith('/v1/privacy/erasures') && response.request().method() === 'POST')
  await confirm(page, '发起全局隐私清除')
  await expect(page).toHaveURL(/operation=.*device=/)
  const receiptURL = page.url()
  // 旧会话失效早于本地清除完成；先读完原响应，避免刷新取消其余 owner 的清除。
  const response = await erased
  expect(response.status()).toBe(202)
  const receipt = await response.json()
  for (const store of ['identity_metadata', 'knowledge_content', 'learning_event_payload']) {
    expect(receipt.steps).toContainEqual(expect.objectContaining({ store, status: 'succeeded' }))
  }
  await expect.poll(async () => (await page.request.get('/v1/web/session')).status()).toBe(401)
  await page.reload()
  await pair(page)
  const repaired = await (await page.request.get('/v1/web/session')).json()
  expect(repaired.device.id).not.toBe(session.device.id)
  expect(repaired.generation).toBe(receipt.learner_generation)
  expect(repaired.generation).toBeGreaterThan(session.generation)
  await page.goto(receiptURL)
  await expect(page.getByRole('region', { name: '隐私清除回执' })).toBeVisible()
  await expect(page.getByRole('region', { name: '隐私清除回执' })).toContainText(receipt.erasure_id)
  await expect(page.getByRole('region', { name: '隐私清除回执' })).toContainText('不在物理擦除保证内')
  expect(await page.content()).not.toContain(grant)
})

test('导师申请必须在内嵌候选面板批准才可取得回执', async ({ page, context }) => {
  test.skip(process.env.WEB_MENTOR_FIXTURE !== '1', '需本地确定性导师 fixture')
  await pair(page, 'settings')
  await page.goto('/app/settings')
  const model = page.getByRole('region', { name: 'Web 导师模型', exact: true })
  await model.getByRole('button', { name: '配置或替换凭据' }).click()
  await model.getByLabel('端点', { exact: true }).fill('http://127.0.0.1:32930/v1')
  await model.getByLabel('模型名称').fill('browser-memory-fixture')
  await model.getByLabel('鉴权方式').selectOption('none')
  await model.getByLabel('启用Web 导师模型').check()
  await model.getByRole('button', { name: '保存Web 导师模型配置' }).click()
  await expect(page.getByText('配置已保存。', { exact: true })).toBeVisible()
  await context.clearCookies()
  await pair(page)
  await page.getByLabel('今天想学会什么？', { exact: true }).fill(`记忆导师 ${randomUUID()}`)
  await page.getByRole('button', { name: '仅保存目标', exact: true }).click()
  await page.getByRole('link', { name: '查看目标', exact: true }).click()
  await page.getByRole('button', { name: '新建对话', exact: true }).click()
  const panel = page.getByRole('region', { name: '目标内导师', exact: true })
  await panel.getByLabel('想和导师讨论什么？').fill('申请保存长期偏好：我长期偏好先看直觉再看公式')
  await panel.getByRole('button', { name: '发起导师交流' }).click()
  await expect(panel.getByRole('region', { name: '记忆候选详情' })).toContainText('我长期偏好先看直觉再看公式')
  await confirm(page, '批准此条记忆')
  await panel.getByRole('button', { name: '已在记忆面板完成审批，核对回执', exact: true }).click()
  await expect(panel.getByLabel('导师输出')).toContainText('浏览器真实导师')
})
