import { test, expect } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { reconnectAndWaitForReads } from './network-recovery'

test('真实浏览器导师、结构化等待、断线重启恢复、预算与清除', async ({ page, context }) => {
  test.skip(process.env.WEB_MENTOR_FIXTURE !== '1', '需要显式启用本地模型 fixture')
  test.setTimeout(120000)
  page.setDefaultTimeout(15000)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  const code = execFileSync('../../server/edu-agentd', ['pairing-code', 'create', '--profile', 'settings'], {
    encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'],
    env: { PATH: process.env.PATH, DATABASE_URL: process.env.TEST_DATABASE_URL, MIGRATE_ON_START: 'true' },
  }).trim()
  await page.goto('/app/')
  await page.getByLabel('配对码', { exact: true }).fill(code)
  await page.getByRole('button', { name: '配对并进入' }).click()
  await page.getByRole('link', { name: '设置与能力' }).click()
  const model = page.getByRole('region', { name: 'Web 导师模型', exact: true })
  await model.getByRole('button', { name: '配置或替换凭据' }).click()
  await model.getByLabel('端点', { exact: true }).fill('http://127.0.0.1:32930/v1')
  await model.getByLabel('模型名称').fill('browser-mentor-fixture')
  await model.getByLabel('鉴权方式').selectOption('none')
  await model.getByLabel('启用Web 导师模型').check()
  await model.getByRole('button', { name: '保存Web 导师模型配置' }).click()
  await expect(page.getByText('配置已保存。', { exact: true })).toBeVisible()
  await page.goto('/app/')
  await page.getByLabel('今天想学会什么？', { exact: true }).fill(`浏览器导师目标 ${randomUUID().slice(0, 8)}`)
  await page.getByRole('button', { name: '仅保存目标', exact: true }).click()
  await page.getByRole('link', { name: '查看目标', exact: true }).click()
  const goalURL = page.url()
  await page.getByRole('button', { name: '新建对话', exact: true }).click()
  const panel = page.getByRole('region', { name: '目标内导师', exact: true })
  const prompt = panel.getByLabel('想和导师讨论什么？')
  await expect(prompt).toBeEnabled()
  await prompt.fill('请做一次结构化目标理解')
  await prompt.dispatchEvent('compositionstart')
  await prompt.dispatchEvent('keydown', { key: 'Enter', code: 'Enter', isComposing: true })
  await prompt.dispatchEvent('compositionend')
  await expect(panel.getByText(/等待你的回答/)).toHaveCount(0)
  await panel.getByRole('button', { name: '发起导师交流' }).click()
  await expect(panel.getByText('先从哪个方向理解？')).toBeVisible()
  await page.reload()
  await expect(panel.getByText('先从哪个方向理解？')).toBeVisible()
  await page.getByRole('link', { name: '任务中心', exact: true }).click()
  await page.getByRole('combobox', { name: '任务类型', exact: true }).selectOption('mentor')
  await page.getByRole('combobox', { name: '运行状态', exact: true }).selectOption('waiting_input')
  await page.getByRole('link', { name: '查看原运行', exact: true }).click()
  await expect(page.getByText('先从哪个方向理解？')).toBeVisible()
  const runURL = page.url()
  await page.getByRole('link', { name: '关闭详情并返回任务中心' }).click()
  await page.goto(runURL)
  await expect(page.getByText('先从哪个方向理解？')).toBeVisible()
  await page.getByRole('button', { name: '直觉', exact: true }).click()
  await expect(page.getByRole('heading', { name: '目标内导师 · 已完成' })).toBeVisible()
  await page.goto(goalURL)
  await expect(panel.getByRole('status')).toContainText('已完成')
  await expect(panel.getByLabel('导师输出')).toContainText('浏览器真实导师：已读取本次绑定目标。')
  const stats = await (await page.request.get('http://127.0.0.1:32930/stats')).json()
  await reconnectAndWaitForReads(page, context, '/v1/tutoring/sessions')
  await page.reload()
  await expect(panel.getByRole('status')).toContainText('已完成')
  const supervisor = JSON.parse(await readFile('/tmp/edu-web-test-server-32929.json', 'utf8'))
  process.kill(supervisor.supervisor, 'SIGUSR2')
  await expect.poll(async () => JSON.parse(await readFile('/tmp/edu-web-test-server-32929.json', 'utf8')).child, { timeout: 30000 }).not.toBe(supervisor.child)
  await expect.poll(async () => { try { return (await page.request.get('/livez')).status() } catch { return 0 } }).toBe(200)
  await page.goto(goalURL)
  await expect(panel.getByLabel('导师输出')).toContainText('浏览器真实导师')
  expect((await (await page.request.get('http://127.0.0.1:32930/stats')).json()).calls).toBe(stats.calls)
  const other = await context.newPage()
  // 先确认第二页已建立订阅，避免仅由初始快照请求碰巧读到清除结果。
  const subscribed = other.waitForResponse((response) => response.url().includes('/events?after=') && response.status() === 200)
  await other.goto(goalURL)
  await expect(other.getByLabel('导师输出')).toContainText('浏览器真实导师')
  await subscribed
  await panel.getByRole('button', { name: '清除本次正文', exact: true }).click()
  await page.getByRole('button', { name: '确认清除本次正文' }).click()
  await expect(panel.getByLabel('导师输出')).not.toContainText('浏览器真实导师')
  await expect(other.getByLabel('导师输出')).not.toContainText('浏览器真实导师')
  await other.close()
  await prompt.fill('预算等待场景')
  await panel.getByText('本次模型预算', { exact: true }).click()
  await panel.getByLabel('Token 预留上限').fill('1')
  await panel.getByRole('button', { name: '发起导师交流' }).click()
  await expect(panel.getByRole('status')).toContainText('预算已用完')
  await panel.getByRole('button', { name: '不增加预算，停止' }).click()
  await expect(panel.getByRole('status')).toContainText('已停止')
  expect((await (await page.request.get('http://127.0.0.1:32930/stats')).json()).calls).toBe(stats.calls)
  for (const width of [390, 768, 1280]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))).not.toContain('导师')
  expect(errors).toEqual([])
})
