import { test, expect, type Page } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import { readFile } from 'node:fs/promises'

async function configure(page: Page, endpoint = 'http://127.0.0.1:32930/v1') {
  await page.goto('/app/settings')
  const model = page.getByRole('region', { name: 'Web 导师模型', exact: true })
  await model.getByRole('button', { name: '配置或替换凭据' }).click()
  await model.getByLabel('端点', { exact: true }).fill(endpoint)
  await model.getByLabel('模型名称').fill('browser-history-fixture')
  await model.getByLabel('鉴权方式').selectOption('none')
  await model.getByLabel('启用Web 导师模型').check()
  await model.getByRole('button', { name: '保存Web 导师模型配置' }).click()
  await expect(page.getByText('配置已保存。', { exact: true })).toBeVisible()
}

test('真实导师历史：多轮、展开草稿、回执核对、端点确认、删除和临时重启', async ({ page }) => {
  test.skip(process.env.WEB_MENTOR_FIXTURE !== '1', '需要本地确定性导师 fixture')
  test.setTimeout(150000)
  const code = execFileSync('../../server/edu-agentd', ['pairing-code', 'create', '--profile', 'settings'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], env: { PATH: process.env.PATH, DATABASE_URL: process.env.TEST_DATABASE_URL, MIGRATE_ON_START: 'true' } }).trim()
  await page.goto('/app/')
  await page.getByLabel('配对码', { exact: true }).fill(code)
  await page.getByRole('button', { name: '配对并进入' }).click()
  await configure(page)
  await page.goto('/app/')
  await page.getByLabel('今天想学会什么？', { exact: true }).fill(`历史验收 ${randomUUID().slice(0, 8)}`)
  await page.getByRole('button', { name: '仅保存目标', exact: true }).click()
  await page.getByRole('link', { name: '查看目标', exact: true }).click()
  const goalURL = page.url()
  await page.getByRole('button', { name: '新建对话', exact: true }).click()
  const panel = page.getByRole('region', { name: '目标内导师', exact: true })
  const prompt = panel.getByLabel('想和导师讨论什么？')
  await prompt.fill('第一轮历史问题')
  await panel.getByRole('button', { name: '发起导师交流' }).click()
  await expect(panel.getByRole('status')).toContainText('已完成')
  await prompt.fill('展开后应保留的草稿')
  const before = await (await page.request.get('http://127.0.0.1:32930/stats')).json()
  await page.getByRole('link', { name: '展开导师对话' }).click()
  const chatURL = page.url()
  await expect(prompt).toHaveValue('展开后应保留的草稿')
  await page.getByRole('link', { name: '返回原目标' }).click()
  await expect(prompt).toHaveValue('展开后应保留的草稿')
  expect((await (await page.request.get('http://127.0.0.1:32930/stats')).json()).calls).toBe(before.calls)
  // 正式服务已接收，浏览器丢失响应；随后只能核对原回执。
  await page.route('**/v1/learning/conversations/*/turns', async (route) => { await route.fetch(); await route.abort('failed') }, { times: 1 })
  await panel.getByRole('button', { name: '发起导师交流' }).click()
  await panel.getByRole('button', { name: '核对提交结果' }).click()
  await expect(prompt).toHaveValue('')
  await expect(panel.getByRole('status')).toContainText('已完成')
  const after = await (await page.request.get('http://127.0.0.1:32930/stats')).json()
  expect(after.calls).toBe(before.calls + 1)
  expect(after.historyRequests).toBeGreaterThan(before.historyRequests)
  await page.getByLabel('对话新名称').fill('可检索的导师历史')
  await page.getByRole('button', { name: '重命名对话' }).click()
  await expect(page.getByRole('heading', { name: '可检索的导师历史' })).toBeVisible()
  await page.getByLabel('搜索对话标题').fill('可检索')
  await expect(page.getByRole('button', { name: '可检索的导师历史', exact: true })).toBeVisible()
  await configure(page, 'http://127.0.0.1:32930/alternate')
  await page.goto(chatURL)
  await expect(page.getByText('模型目的地已变化，当前仅查看')).toBeVisible()
  await expect(prompt).toBeDisabled()
  expect((await (await page.request.get('http://127.0.0.1:32930/stats')).json()).calls).toBe(after.calls)
  await page.getByLabel('同意将上述历史发送到此目的地').check()
  await prompt.fill('确认目的地后的第三轮')
  await panel.getByRole('button', { name: '发起导师交流' }).click()
  await expect(panel.getByRole('status')).toContainText('已完成')
  await page.goto(goalURL)
  await page.getByRole('button', { name: '删除对话：可检索的导师历史', exact: true }).click()
  await page.getByRole('button', { name: '确认删除对话：可检索的导师历史' }).click()
  await expect(page.getByText('服务器已确认删除对话；目标、内容、活动和 Evidence 保留。')).toBeVisible()
  await expect(page.getByRole('button', { name: '可检索的导师历史', exact: true })).toHaveCount(0)
  await page.getByLabel('新对话保存到服务器').uncheck()
  await page.getByRole('button', { name: '新建对话', exact: true }).click()
  await prompt.fill('临时正文不应在重启后恢复')
  await panel.getByRole('button', { name: '发起导师交流' }).click()
  await expect(panel.getByRole('status')).toContainText('已完成')
  const supervisor = JSON.parse(await readFile('/tmp/edu-web-test-server-32929.json', 'utf8'))
  process.kill(supervisor.supervisor, 'SIGUSR2')
  await expect.poll(async () => JSON.parse(await readFile('/tmp/edu-web-test-server-32929.json', 'utf8')).child, { timeout: 30000 }).not.toBe(supervisor.child)
  await expect.poll(async () => { try { return (await page.request.get('/livez')).status() } catch { return 0 } }).toBe(200)
  await page.reload()
  await expect(page.getByText('临时正文无法恢复。请新建对话，正式学习事实仍然保留。')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))).not.toContain('临时正文')
})
